import { useEffect, useState } from 'react';
import { Card, PageHeader } from '../components/PageHeader.jsx';
import { EmptyState, LoadingBlock } from '../components/Feedback.jsx';
import { adminApi, API_URL } from '../lib/api.js';
import { useConfirm } from '../components/ConfirmProvider.jsx';

const config={banners:{title:'Banners',empty:'Create the first homepage banner.',fields:[['heading','Heading'],['description','Description'],['buttonText','Button text'],['buttonLink','Button link'],['imageUrl','Image URL']]},faqs:{title:'FAQs',empty:'Create the first customer question.',fields:[['question','Question'],['answer','Answer']]},socials:{title:'Social links',empty:'Add your first social profile.',fields:[['platform','Platform'],['url','HTTPS URL']]}};
const blank=(kind)=>({...Object.fromEntries(config[kind].fields.map(([key])=>[key,''])),displayOrder:0,isActive:true});
export default function CmsCollectionsPage({route}) { const kind=route.id.replace('cms-',''); const meta=config[kind]; const [items,setItems]=useState([]),[form,setForm]=useState(blank(kind)),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''); const confirm=useConfirm(); const load=()=>{setLoading(true);adminApi.cms.list(kind).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));}; useEffect(load,[kind]); const change=(key,value)=>setForm(v=>({...v,[key]:value})); const save=async e=>{e.preventDefault();setSaving(true);setError('');try{if(form._id) await adminApi.cms.update(kind,form._id,form); else await adminApi.cms.create(kind,form);setForm(blank(kind));load();}catch(e){setError(e.message)}finally{setSaving(false)}}; const remove=async item=>{if(await confirm({title:`Delete ${meta.title.slice(0,-1)}?`,tone:'danger',message:'This removes it from the customer website.'})){await adminApi.cms.remove(kind,item._id);load();}}; const upload=async file=>{if(!file)return;setSaving(true);try{const result=await adminApi.cms.uploadImage(file);change('imageUrl',`${API_URL}${result.url}`)}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <><PageHeader eyebrow="STOREFRONT CMS" title={meta.title} description="Saved changes publish to the customer website immediately."/><div className="admin-dashboard-columns"><Card title={form._id?'Edit item':'New item'}><form className="admin-stack" onSubmit={save}>{meta.fields.map(([key,label])=><label className="store-content-field" key={key}><span>{label}</span>{key==='description'||key==='answer'?<textarea rows="4" value={form[key]} onChange={e=>change(key,e.target.value)}/>:<input required={key!=='buttonText'&&key!=='buttonLink'} value={form[key]} onChange={e=>change(key,e.target.value)}/>}</label>)}{kind==='banners'&&<label className="store-content-field"><span>Upload image (JPEG, PNG, WebP; max 5 MB)</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/>{form.imageUrl&&<img src={form.imageUrl} alt="Banner preview" style={{maxWidth:'100%',maxHeight:160,objectFit:'cover'}}/>}</label>}<label className="store-content-field"><span>Display order</span><input type="number" min="0" value={form.displayOrder} onChange={e=>change('displayOrder',Number(e.target.value))}/></label><label><input type="checkbox" checked={form.isActive} onChange={e=>change('isActive',e.target.checked)}/> Active on website</label>{error&&<p className="admin-alert admin-alert-error">{error}</p>}<button className="admin-btn admin-btn-primary" disabled={saving}>{saving?'Saving…':'Save and publish'}</button>{form._id&&<button type="button" className="admin-btn admin-btn-ghost" onClick={()=>setForm(blank(kind))}>Cancel edit</button>}</form></Card><Card title={`Published ${meta.title}`}>{loading?<LoadingBlock/>:items.length?<div className="admin-stack">{items.map(item=><article className="admin-card" key={item._id}><b>{item.heading||item.question||item.platform}</b><p className="admin-hint">{item.description||item.answer||item.url}</p><p className="admin-hint">Order {item.displayOrder} · {item.isActive?'Active':'Inactive'}</p><button className="admin-btn admin-btn-ghost" onClick={()=>setForm(item)}>Edit</button> <button className="admin-btn admin-btn-danger" onClick={()=>remove(item)}>Delete</button></article>)}</div>:<EmptyState title="Nothing here yet" description={meta.empty}/>}</Card></div></>; }
