import { useState } from 'react';
import { Card, PageHeader } from '../components/PageHeader.jsx';
import { EmptyState, ErrorState } from '../components/Feedback.jsx';
import { adminApi } from '../lib/api.js';
import { formatDateTime } from '../lib/format.js';
import { useResource } from '../lib/useResource.js';
import { useToast } from '../components/ToastProvider.jsx';

const empty = () => ({ name: '', discountType: 'percentage', amount: '', cap: '', products: '', categories: '', startsAt: '', endsAt: '', priority: '0', isStackable: false });
const localDate = (value) => { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
export default function OffersPage() {
  const toast = useToast(); const { data, error, reload } = useResource(() => adminApi.offers.list(), []); const [form, setForm] = useState(empty); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(null);
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const create = async (event) => { event.preventDefault(); setBusy(true); try {
    const amount = Number(form.amount), value = form.discountType === 'percentage' ? Math.round(amount * 100) : Math.round(amount * 100);
    const payload = { name: form.name.trim(), discountType: form.discountType, discountValue: value, maximumSavingPaise: Math.round(Number(form.cap || 0) * 100), productSlugs: form.products.split(',').map((item) => item.trim()).filter(Boolean), categories: form.categories.split(',').map((item) => item.trim()).filter(Boolean), startsAt: form.startsAt ? new Date(form.startsAt).toISOString() : undefined, endsAt: form.endsAt ? new Date(form.endsAt).toISOString() : undefined, priority: Number(form.priority || 0), isStackable: form.isStackable, isActive: true };
    if (editing) await adminApi.offers.update(editing, payload); else await adminApi.offers.create(payload);
    setForm(empty()); setEditing(null); toast.success(editing ? 'Offer updated.' : 'Offer created.'); reload();
  } catch (failure) { toast.error(failure.message); } finally { setBusy(false); } };
  const edit = (offer) => { setEditing(offer._id); setForm({ name: offer.name, discountType: offer.discountType, amount: String(offer.discountValue / 100), cap: String((offer.maximumSavingPaise ?? 0) / 100), products: (offer.productSlugs ?? []).join(', '), categories: (offer.categories ?? []).join(', '), startsAt: localDate(offer.startsAt), endsAt: localDate(offer.endsAt), priority: String(offer.priority ?? 0), isStackable: Boolean(offer.isStackable) }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <><PageHeader eyebrow="MARKETING" title="Offers" description="Schedule product, category or storewide discounts. Prices are calculated on the server." />
    <Card title="New offer" description="Percentages use basis points in storage. Add product slugs or category names to limit an offer; leave both blank for storewide.">
      <form className="admin-stack" onSubmit={create}>
        <div className="admin-toolbar"><input className="admin-input" required placeholder="Offer name" value={form.name} onChange={(event) => change('name', event.target.value)} /><select className="admin-input" value={form.discountType} onChange={(event) => change('discountType', event.target.value)}><option value="percentage">Percentage</option><option value="flat">Fixed amount</option></select><input className="admin-input" type="number" min="0.01" step="0.01" max={form.discountType === 'percentage' ? 100 : undefined} required placeholder={form.discountType === 'percentage' ? 'Discount %' : 'Discount ₹'} value={form.amount} onChange={(event) => change('amount', event.target.value)} /></div>
        <div className="admin-toolbar"><input className="admin-input" placeholder="Product slugs, comma-separated" value={form.products} onChange={(event) => change('products', event.target.value)} /><input className="admin-input" placeholder="Category names, comma-separated" value={form.categories} onChange={(event) => change('categories', event.target.value)} /><input className="admin-input" type="number" min="0" step="0.01" placeholder="Max saving ₹ (optional)" value={form.cap} onChange={(event) => change('cap', event.target.value)} /></div>
        <div className="admin-toolbar"><label className="admin-field">Starts at<input className="admin-input" type="datetime-local" value={form.startsAt} onChange={(event) => change('startsAt', event.target.value)} /></label><label className="admin-field">Ends at<input className="admin-input" type="datetime-local" value={form.endsAt} onChange={(event) => change('endsAt', event.target.value)} /></label><label className="admin-field">Priority<input className="admin-input" type="number" value={form.priority} onChange={(event) => change('priority', event.target.value)} /></label><label className="admin-check"><input type="checkbox" checked={form.isStackable} onChange={(event) => change('isStackable', event.target.checked)} /> Can stack with lower priority offers</label><button className="admin-btn admin-btn-primary" disabled={busy}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Create offer'}</button>{editing && <button type="button" className="admin-btn admin-btn-ghost" onClick={() => { setEditing(null); setForm(empty()); }}>Cancel edit</button>}</div>
      </form>
    </Card>
    <Card title="Saved offers">{error ? <ErrorState error={error} onRetry={reload} /> : !data?.length ? <EmptyState title="No offers yet" description="Scheduled promotions will appear here." /> : <div className="admin-stack-tight">{data.map((offer) => <article className="admin-row-actions" key={offer._id}><div><b>{offer.name}</b><small className="admin-hint">{offer.discountType === 'percentage' ? `${offer.discountValue / 100}%` : `₹${(offer.discountValue / 100).toFixed(2)}`} · priority {offer.priority} · {offer.isStackable ? 'stackable' : 'not stackable'}</small><small className="admin-hint">{offer.startsAt ? formatDateTime(offer.startsAt) : 'Now'} – {offer.endsAt ? formatDateTime(offer.endsAt) : 'No expiry'}</small></div><span>{offer.isActive ? 'Active' : 'Inactive'}</span><button type="button" className="admin-btn admin-btn-small admin-btn-ghost" onClick={() => edit(offer)}>Edit</button>{offer.isActive ? <button type="button" className="admin-btn admin-btn-small admin-btn-quiet" onClick={() => adminApi.offers.deactivate(offer._id).then(reload).catch((failure) => toast.error(failure.message))}>Deactivate</button> : <button type="button" className="admin-btn admin-btn-small admin-btn-ghost" onClick={() => adminApi.offers.update(offer._id, { isActive: true }).then(reload).catch((failure) => toast.error(failure.message))}>Reactivate</button>}</article>)}</div>}</Card>
  </>;
}
