import { useEffect, useState } from 'react';
import { adminApi } from '../lib/api.js';
import { Card, PageHeader } from '../components/PageHeader.jsx';

const contentFields = [['shippingPolicy','Shipping policy'],['returnPolicy','Returns and refund policy'],['privacyPolicy','Privacy policy'],['terms','Terms and conditions'],['about','About Nutri Heaven'],['contact','Contact details and store address'],['faq','Frequently asked questions']];
const contactFields = [['legalName','Business name'],['supportEmail','Support email'],['supportPhone','Phone'],['whatsappNumber','WhatsApp number'],['businessHours','Business hours']];
export default function StoreContentPage() {
  const [value,setValue]=useState({content:{}}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{adminApi.settings.get().then(record=>setValue(record?.value??{content:{}})).catch(error=>setMessage(error.message)).finally(()=>setLoading(false));},[]);
  const save=async()=>{setSaving(true);setMessage('');try{await adminApi.settings.update(value);setMessage('Store content saved and published.');}catch(error){setMessage(error.message);}finally{setSaving(false);}};
  return <><PageHeader eyebrow="STOREFRONT CMS" title="Store content" description="Edit customer-facing information and policies." actions={<button className="admin-btn admin-btn-primary" onClick={save} disabled={saving||loading}>{saving?'Saving…':'Save and publish'}</button>}/><div className="admin-stack">{message&&<p role="status" className="admin-hint">{message}</p>}<Card title="Shared customer content">{loading?<p>Loading content…</p>:contentFields.map(([key,label])=><label className="store-content-field" key={key}><span>{label}</span><textarea rows={key==='faq'?8:6} value={value.content?.[key]??''} onChange={event=>setValue(current=>({...current,content:{...current.content,[key]:event.target.value}}))}/></label>)}</Card><Card title="Business contact details">{contactFields.map(([key,label])=><label className="store-content-field" key={key}><span>{label}</span><input value={value[key]??''} onChange={event=>setValue(current=>({...current,[key]:event.target.value}))}/></label>)}<label className="store-content-field"><span>Store address</span><textarea rows="3" value={value.address??''} onChange={event=>setValue(current=>({...current,address:event.target.value}))}/></label></Card></div></>;
}
