import { BadRequestException, ConflictException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { JwtService } from '@nestjs/jwt';
import { createHash, randomBytes } from 'crypto';
import { compare, hash } from 'bcryptjs';
import { Model } from 'mongoose';
import { Order, OrderDocument } from '../orders/order.schema';
import { Product, ProductDocument } from '../products/product.schema';
import { AddressDto, SignupDto, UpdateProfileDto } from './customer.dto';
import { Customer, CustomerAddress, CustomerDocument } from './customer.schema';

const publicCustomer = (customer: CustomerDocument | Record<string, any>) => ({ id: String(customer._id), name: customer.name, email: customer.email, phone: customer.phone ?? '', addresses: customer.addresses ?? [], wishlist: customer.wishlist ?? [] });

@Injectable()
export class CustomerService {
  constructor(@InjectModel(Customer.name) private readonly customers: Model<CustomerDocument>, @InjectModel(Product.name) private readonly products: Model<ProductDocument>, @InjectModel(Order.name) private readonly orders: Model<OrderDocument>, private readonly jwt: JwtService) {}
  private async token(customer: CustomerDocument) { return this.jwt.signAsync({ sub: String(customer._id), email: customer.email, type: 'customer' }, { expiresIn: '7d' }); }
  async signup(dto: SignupDto) {
    try { const customer = await this.customers.create({ name: dto.name.trim(), email: dto.email.toLowerCase(), passwordHash: await hash(dto.password, 12), phone: dto.phone, addresses: [], wishlist: [] }); return { accessToken: await this.token(customer), customer: publicCustomer(customer) }; }
    catch (error) { if (typeof error === 'object' && error && 'code' in error && error.code === 11000) throw new ConflictException('An account already exists for this email'); throw error; }
  }
  async login(email: string, password: string) { const customer = await this.customers.findOne({ email: email.toLowerCase(), isActive: true }).select('+passwordHash').exec(); if (!customer || !await compare(password, customer.passwordHash)) throw new UnauthorizedException('Invalid email or password'); return { accessToken: await this.token(customer), customer: publicCustomer(customer) }; }
  async me(id: string) { const customer = await this.customers.findById(id).lean().exec(); if (!customer || !customer.isActive) throw new UnauthorizedException('Customer account is unavailable'); return publicCustomer(customer); }
  async update(id: string, dto: UpdateProfileDto) { const customer = await this.customers.findByIdAndUpdate(id, { $set: dto }, { new: true, runValidators: true }).exec(); if (!customer) throw new NotFoundException('Customer not found'); return publicCustomer(customer); }
  async addAddress(id: string, dto: AddressDto) { const customer = await this.customers.findById(id).exec(); if (!customer) throw new NotFoundException('Customer not found'); const address: CustomerAddress = { ...dto, id: randomBytes(12).toString('hex'), isDefault: customer.addresses.length === 0 } as CustomerAddress; customer.addresses.push(address); await customer.save(); return publicCustomer(customer).addresses; }
  async updateAddress(id: string, addressId: string, dto: AddressDto) { const customer = await this.customers.findById(id).exec(); const index = customer?.addresses.findIndex(address => address.id === addressId) ?? -1; if (index < 0 || !customer) throw new NotFoundException('Address not found'); const existing = customer.addresses[index]; if (!existing) throw new NotFoundException('Address not found'); customer.addresses[index] = { ...existing, ...dto, id: addressId, isDefault: existing.isDefault }; await customer.save(); return publicCustomer(customer).addresses; }
  async deleteAddress(id: string, addressId: string) { const customer = await this.customers.findById(id).exec(); if (!customer) throw new NotFoundException('Customer not found'); const old = customer.addresses.length; customer.addresses = customer.addresses.filter(address => address.id !== addressId); if (old === customer.addresses.length) throw new NotFoundException('Address not found'); const first = customer.addresses[0]; if (first && !customer.addresses.some(address => address.isDefault)) first.isDefault = true; await customer.save(); return publicCustomer(customer).addresses; }
  async addWishlist(id: string, slug: string) { const product = await this.products.findOne({ slug, isActive: true }).lean().exec(); if (!product) throw new NotFoundException('Product is no longer available'); await this.customers.findByIdAndUpdate(id, { $addToSet: { wishlist: slug } }).exec(); return this.wishlist(id); }
  async removeWishlist(id: string, slug: string) { await this.customers.findByIdAndUpdate(id, { $pull: { wishlist: slug } }).exec(); return this.wishlist(id); }
  async wishlist(id: string) { const customer = await this.customers.findById(id).lean().exec(); if (!customer) throw new NotFoundException('Customer not found'); return this.products.find({ slug: { $in: customer.wishlist ?? [] }, isActive: true }).lean().exec(); }
  async ordersFor(email: string) { return this.orders.find({ customerEmail: email.toLowerCase() }).sort({ createdAt: -1 }).lean().exec(); }
  async forgotPassword(email: string) { const customer = await this.customers.findOne({ email: email.toLowerCase(), isActive: true }).select('+passwordResetHash +passwordResetExpiresAt').exec(); if (!customer) return { message: 'If an account exists, reset instructions have been sent.' }; const token = randomBytes(32).toString('hex'); customer.passwordResetHash = createHash('sha256').update(token).digest('hex'); customer.passwordResetExpiresAt = new Date(Date.now() + 15 * 60 * 1000); await customer.save(); const result: Record<string, string> = { message: 'If an account exists, reset instructions have been sent.' }; if (process.env.NODE_ENV !== 'production') result.resetToken = token; return result; }
  async resetPassword(token: string, password: string) { const passwordResetHash = createHash('sha256').update(token).digest('hex'); const customer = await this.customers.findOne({ passwordResetHash, passwordResetExpiresAt: { $gt: new Date() }, isActive: true }).select('+passwordResetHash +passwordResetExpiresAt').exec(); if (!customer) throw new BadRequestException('Reset link is invalid or expired'); customer.passwordHash = await hash(password, 12); customer.passwordResetHash = undefined; customer.passwordResetExpiresAt = undefined; await customer.save(); return { accessToken: await this.token(customer), customer: publicCustomer(customer) }; }
  async adminList(q = '', limit = 50, offset = 0) { const needle = q.trim(); const query = needle ? { $or: [{ name: new RegExp(needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') }, { email: new RegExp(needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') }, { phone: new RegExp(needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') }] } : {}; const [items,total] = await Promise.all([this.customers.find(query).sort({ createdAt:-1 }).skip(offset).limit(Math.min(limit,100)).lean().exec(), this.customers.countDocuments(query)]); const emails = items.map(item => item.email); const spend = await this.orders.aggregate([{ $match: { customerEmail: { $in: emails }, status: { $ne: 'cancelled' } } }, { $group: { _id: '$customerEmail', totalSpendingPaise: { $sum: '$totalPaise' }, orders: { $sum: 1 }, lastOrder: { $max: '$createdAt' } } }]); const sums = new Map(spend.map(item => [item._id, item])); return { items: items.map(item => ({ ...publicCustomer(item), ...(sums.get(item.email) ?? { totalSpendingPaise: 0, orders: 0, lastOrder: null }) })), total, limit: Math.min(limit,100), offset }; }
  async adminGet(id: string) { const customer = await this.me(id); return { ...customer, orders: await this.ordersFor(customer.email) }; }
}
